/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as AboutRouteRouteImport } from './routes/about/route'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as UsersIdRouteRouteImport } from './routes/users/$id/route'
import { Route as UsersIndexRouteRouteImport } from './routes/users/index/route'

const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRouteRoute = UsersIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UsersRouteRoute,
} as any)
const UsersIndexRouteRoute = UsersIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => UsersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/about': typeof AboutRouteRoute
  '/users': typeof UsersRouteRouteWithChildren
  '/users/': typeof UsersIndexRouteRoute
  '/users/$id': typeof UsersIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/about': typeof AboutRouteRoute
  '/users': typeof UsersIndexRouteRoute
  '/users/$id': typeof UsersIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/about': typeof AboutRouteRoute
  '/users': typeof UsersRouteRouteWithChildren
  '/users/': typeof UsersIndexRouteRoute
  '/users/$id': typeof UsersIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/users' | '/users/' | '/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/users' | '/users/$id'
  id: '__root__' | '/' | '/about' | '/users' | '/users/' | '/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  AboutRouteRoute: typeof AboutRouteRoute
  UsersRouteRoute: typeof UsersRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/users/': {
      id: '/users/'
      path: ''
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteRouteImport
      parentRoute: typeof UsersRouteRoute
    }
  }
}

interface UsersRouteRouteChildren {
  UsersIndexRouteRoute: typeof UsersIndexRouteRoute
  UsersIdRouteRoute: typeof UsersIdRouteRoute
}

const UsersRouteRouteChildren: UsersRouteRouteChildren = {
  UsersIndexRouteRoute: UsersIndexRouteRoute,
  UsersIdRouteRoute: UsersIdRouteRoute,
}

const UsersRouteRouteWithChildren = UsersRouteRoute._addFileChildren(
  UsersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  AboutRouteRoute: AboutRouteRoute,
  UsersRouteRoute: UsersRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
